services:
  postgres:
    image: postgis/postgis:16-3.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: zoadex
      POSTGRES_USER: zoadex
      POSTGRES_PASSWORD: zoadex
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
